create extension if not exists "pgcrypto";
create table if not exists users (id uuid primary key default gen_random_uuid(), email text unique, phone text, role text not null, status text not null default 'pending', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists customer_profiles (id uuid primary key default gen_random_uuid(), user_id uuid references users(id), name text not null, phone text not null, email text, default_address text, memo text, created_at timestamptz default now(), updated_at timestamptz default now(), deleted_at timestamptz);
create table if not exists business_member_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), company_name text not null, representative_name text not null, business_registration_number text not null, phone text not null, address text not null, verification_document_url text, approval_status text default 'pending', approved_at timestamptz, rejected_reason text, business_price_tier text default 'basic', admin_memo text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists installer_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), name text not null, phone text not null, company_name text not null, business_registration_number text, service_regions text[] default '{}', available_schedule jsonb default '{}'::jsonb, specialties text[] default '{}', approval_status text default 'pending', insurance_status text default 'not_submitted', insurance_provider text, insurance_policy_number text, insurance_document_url text, qualification_notes text, admin_memo text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists admin_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), admin_role text not null, name text not null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists product_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, parent_id uuid references product_categories(id), sort_order int default 0, is_active boolean default true);
create table if not exists product_brands (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, is_primary boolean default false, is_active boolean default true);
create table if not exists products (id uuid primary key default gen_random_uuid(), category_id uuid references product_categories(id), brand_id uuid references product_brands(id), name text not null, slug text unique not null, model_name text, short_description text, detailed_description text, capacity text, heating_area text, fuel_type text, installation_type text, public_price numeric(12,0) not null, business_price numeric(12,0), smartstore_url text, images text[] default '{}', tags text[] default '{}', stock_quantity int, stock_status text default 'unknown', is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
-- omitted repetitive tables in this snippet for brevity in MVP file; include key operational ones
create table if not exists installation_requests (id uuid primary key default gen_random_uuid(), tracking_code text unique not null, customer_name text not null, phone text not null, address text not null, detailed_address text, region text not null, purchase_source text default 'unknown', smartstore_order_number text, product_id uuid references products(id), existing_boiler_brand text, existing_boiler_model text, home_size text, flue_type text, preferred_date date, preferred_time_range text, site_photo_urls text[] default '{}', notes text, status text default '설치중개 신청됨', standard_installation_fee numeric(12,0), additional_fee_note text, privacy_consent boolean not null, marketing_consent boolean default false, priority_level text default 'normal', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists notification_logs (id uuid primary key default gen_random_uuid(), recipient_name text, recipient_phone text, channel text not null, template_key text, message text not null, status text default 'created', related_type text, related_id uuid, created_at timestamptz default now());
alter table products enable row level security;
create policy "public read products" on products for select using (is_active = true);
