-- ins-way MVP schema (abridged but production-ready foundation)
create extension if not exists "pgcrypto";
create table if not exists public.users (id uuid primary key default gen_random_uuid(), email text unique, phone text, role text not null check (role in ('customer','business_member','installer','admin')), status text not null default 'pending', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.product_brands (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, is_primary boolean default false, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.product_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, parent_id uuid references public.product_categories(id), sort_order int default 0, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), category_id uuid references public.product_categories(id), brand_id uuid references public.product_brands(id), name text not null, slug text unique not null, model_name text, short_description text, detailed_description text, capacity text, heating_area text, fuel_type text, installation_type text, public_price numeric not null default 0, business_price numeric not null default 0, smartstore_url text, images text[] default '{}', tags text[] default '{}', stock_quantity int, stock_status text default 'unknown', is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.installation_requests (id uuid primary key default gen_random_uuid(), tracking_code text unique not null, customer_name text not null, phone text not null, address text not null, detailed_address text, region text not null, purchase_source text default 'unknown', smartstore_order_number text, existing_boiler_brand text, existing_boiler_model text, home_size text, flue_type text, preferred_date date, preferred_time_range text, site_photo_urls text[] default '{}', notes text, status text not null default '설치중개 신청됨', privacy_consent boolean not null, marketing_consent boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.notification_logs (id uuid primary key default gen_random_uuid(), recipient_name text, recipient_phone text, channel text not null, template_key text not null, message text not null, status text not null default 'created', related_type text, related_id uuid, created_at timestamptz default now());
alter table public.products enable row level security;
create policy "public can read active products" on public.products for select using (is_active=true);
